### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by huberfelix0** [topocm/topocm_content#1]
topocm_content/w1_topointro/0d.ipynb

CHPT: The concept of a topological invariant
Below, we plot the energy levels along our path from H to H′ again, together with our topological invariant, the number of filled energy levels. You can see that this number changes from 2 to 3. Hence we can say that H and H′ are not topologically equivalent.

should probably state "...changes from 5 to 6."

**Comment by akhmerov** [comment]
Thanks :)
