### ISSUE TITLE
Static deployment

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#103]
Instead of masked redirect to nbviewer, let's make an actual website at http://topocondmat.org. This has an advantage that URLs become persistent and human-readable.

For a start we don't need much beyond just running `nbconvert --to html` on every single notebook, however we also need to copy the images and translate links inside the notebooks. Afterwards we can easily introduce our custom html template.

**Comment by torosdahl** [comment]
eedbb0d3bbf7bfe435486a5177730156ac1d0587

**Comment by akhmerov** [comment]
Live now; thanks @torosdahl @basnijholt!

We can incrementally improve the template, but it's already OK for now.
