### ISSUE TITLE
Cached output filter shouldn't store evaluations with errors (also it should inform about errors)

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#117]
Right now if some evaluation fails for no good reason (wrong library version, lack of internet connection, etc), the cache is populated with an error message essentially. We should treat these cases more reasonably by not storing erroneous evaluations in cache, and notifying the user that an error has occurred.

**Comment by akhmerov** [comment]
Pinging @torosdahl

**Comment by irfanphy** [comment]
closed with f4f7bebfccf7e181dcd2481301bd1072645cb25a
