### ISSUE TITLE
Typo in equation for Majorana operators in 1.2

### ISSUE THREAD

**Issue by bernardvanheck** [topocm/topocm_content#121]
In the subsection 'Kitaev chain model', we should have $\gamma_{2n}=i(c^\dagger_n-c^n)$ to maintain sign consistency between the Hamiltonians written in terms of Majorana and fermionic operators. (Probably the consistency of notation should be checked in the other equations of the section as well.)

**Comment by bernardvanheck** [comment]
See question on edX:

https://courses.edx.org/courses/course-v1:DelftX+TOPOCMx+1T2016/discussion/forum/ec783e7c7ccc36284d4393a4722d6cf2/threads/56ba74312d96fe0510000790

**Comment by basnijholt** [comment]
@bernardvanheck I made the sign fix [here](https://gitlab.kwant-project.org/qt/topocm/merge_requests/34).

Could you please check the [test website page](https://test.topocondmat.org/w1_topointro/1D.html)?

**Comment by akhmerov** [comment]
Should be good now.
