### ISSUE TITLE
week 2 plotting bugs

### ISSUE THREAD

**Issue by irfanphy** [topocm/topocm_content#124]
1. The xticks of the function  plot_spectrum_nanowire(fluxes, spectrum) in w2_majorana/signatures.ipynb are not working and gives wrong ticks

2. w2_majorana/nanowire.ipynb: First band-structure plot in subsec  s-wave superconductor with magnetic field : delta is equal to 0.1  instead of 0.0

**Comment by basnijholt** [comment]
Fixed in e0f8ed0
