### ISSUE TITLE
Use LaTeX ticks by default

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#130]

**Comment by basnijholt** [comment]
Works with 
```
import holoviews as hv
hv.notebook_extension('matplotlib')
from holoviews.plotting.mpl import MPLPlot
MPLPlot.fig_rcparams['text.usetex'] = True
hv.Curve(range(10))
```

However when using custom ticks it defaults to normal style.

**Comment by akhmerov** [comment]
Go ahead and add it, sounds good.

**Comment by philippjfr** [comment]
Would be good if you handled it for now as I can't promise we'll have time to investigate it in HoloViews in the near future but if you could add an issue to improve LaTeX support in HoloViews that would be helpful.
