### ISSUE TITLE
w7_defects/ti_majoranas.ipynb densities**0.25?

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#145]
In the second plot of w7_defects/ti_majoranas.ipynb the densities are raised to the power 1/4th, and I have no idea why. Was this just to make the values visible? In that case we should remove the numbers, or don't use a linear cmap.

`kwant.plotter.map(sys, densities[:,0]**0.25, cmap='gist_heat_r', show=False)`

**Comment by akhmerov** [comment]
Your guess is correct. A nonliner cmap would be the best resolution.

**Comment by basnijholt** [comment]
What about:
```python
import matplotlib.cm
import matplotlib.colors as mcolors
colors = matplotlib.cm.gist_heat_r(np.linspace(0, 1, 128)**.25)
nonlinearcmap = mcolors.LinearSegmentedColormap.from_list('nonlinearcmap', colors)

p = SimpleNamespace(t=1.0, mu=0.4, delta=0.5, phase=lambda x, y: np.angle(x+1j*y))
l = 60
w = 60
sys = make_2d_pwave(w,l)
energies, states, densities = calc_energies(sys, p, num_orbitals=2, num_states=10)
kwant.plotter.map(sys, densities[:,0], cmap=nonlinearcmap, show=False)
plt.show()
```
![download 1](https://cloud.githubusercontent.com/assets/6897215/13851438/78ae8a44-ec5e-11e5-88ea-0f7d36d889c6.png)


the image aims to show that the wf is mostly near the edge and center.

**Comment by akhmerov** [comment]
Looks good to me. The colorbar now needs to be truncated or hidden though :)

**Comment by basnijholt** [comment]
Renamed in a7be2ff.
