### ISSUE TITLE
Static plot recalculated in HoloMaps in w7_defects/crystalline_defects.ipynb

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#148]
The plot that is not changed shouldn't be recalculated for every parameter.

**Comment by akhmerov** [comment]
What do you mean?

**Comment by basnijholt** [comment]
Spectrum is calculated for a lot of points, but doesn't change. The only thing that changes is the points on top of the spectrum.

**Comment by akhmerov** [comment]
Ah, you mean an optimization inside the notebook.

**Comment by basnijholt** [comment]
Actually ALL data is available on the first calculation.

**Comment by basnijholt** [comment]
reminder for next iteration, create_edge_dislocation_system and create_screw_system can be combined

**Comment by basnijholt** [comment]
`sorting_mid` argument is not used in `get_densities`

**Comment by basnijholt** [comment]
box is missing in density plots, compare with `edx_2015`

**Comment by basnijholt** [comment]
Addressed in 47c9bb0

**Comment by basnijholt** [comment]
Closing now, issues combined in #152
