### ISSUE TITLE
Incomplete paragraph in w10_extensions/gapless

### ISSUE THREAD

**Issue by torosdahl** [topocm/topocm_content#159]
The first paragraph in the 'Edge states' section ends abruptly.

**Comment by akhmerov** [comment]
cb07fbde0 is at fault here :) 85e6fe338 has the proper text. Perhaps it's good to diff them to see if anything else is missing.

**Comment by torosdahl** [comment]
Closed via 748510235f27b0d2cc8bf9d2b24e65c5f1db4857
