### ISSUE TITLE
Deprecation warning in pretty_fmt_complex

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#168]
![image](https://cloud.githubusercontent.com/assets/2069677/16501618/8dcc0d58-3f0a-11e6-8671-b758e6451789.png)

Numpy now raises a deprecation warning that spoils the output. It seems to be something with the complex formatter, but I don't quite see what exactly at a first glance.

**Comment by basnijholt** [comment]
Fixed in 6078d8c056644abeddf0ca5a51f4a7e5f124a080.
