### ISSUE TITLE
Holoviews >=1.5.0 broken

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#170]
`HoloMap`s don't work anymore on edx, unfortunately. @basnijholt can you take a look? (It's probably related to the changes in style).

**Comment by basnijholt** [comment]
https://github.com/ioam/holoviews/issues/805 will fix this

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
