### ISSUE TITLE
binder setup broken

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#172]
Trying to run a plot with a latex label results in an error:

```
RuntimeError [Call ipython.show_traceback() for details]
LaTeX was not able to process the following string:
b'lp'
```

**Comment by akhmerov** [comment]
If binder still works, we should link to it from the website.

**Comment by basnijholt** [comment]
I've recompiled it and the plots don't work. I think we need to install LaTeX.

**Comment by akhmerov** [comment]
I see there are at least a couple of conda packages with texlive. Maybe those would be enough?

**Comment by basnijholt** [comment]
Let's try: 91180de.

**Comment by basnijholt** [comment]
Didn't work.

**Comment by akhmerov** [comment]
What's the error message?

**Comment by akhmerov** [comment]
Perhaps it's easier to test by just setting up a conda env locally.

**Comment by basnijholt** [comment]
Same error message as before.

**Comment by akhmerov** [comment]
Right now we don't store the notebooks in the repository, let alone their outputs. This makes binder not directly useful to us.

However there's a relatively easy way to fix the problem: we should run the building of the image in the binder's dockerfile. This would be too inefficient if this was triggered by the users, however we can trigger the builds from pipelines for master manually by hitting `mybinder.org/v2/gh/org/repo/ref`.

The only problem about this is that we cannot check whether the binder build succeeded.

**Comment by akhmerov** [comment]
Closing as a duplicate of #230
