### ISSUE TITLE
Plot label missing

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#176]
Zeros and poles plot in `w8_general/invariants.ipynb` has a control variable that says "default", we should be clearer about the physical meaning of it.

Same in `w11_extensions2/floquet.ipynb`: there `n` is once a parameter.

**Comment by basnijholt** [comment]
@akhmerov this is fixed right?

See https://topocondmat.org/w8_general/invariants.html

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
