### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#180]
Stats tracking on topocondmat bears fruit already, it turns out we have a broken URL somewhere. We send people to look at http://nbviewer.jupyter.org/urls/dl.dropboxusercontent.com/u/82809470/Phys839J/Pierels.html
I think it's @jaysau's notebook, and we should include it in the course instead.

**Comment by akhmerov** [comment]
Update, here's the missing notebook: http://nbviewer.jupyter.org/url/antonakhmerov.org/misc/Peierls.ipynb

**Comment by basnijholt** [comment]
Fixed in 76a0aa7.

**Comment by akhmerov** [comment]
This wouldn't work on EdX, right?

**Comment by basnijholt** [comment]
True, maybe we should hard link it to the website once it's there.

**Comment by akhmerov** [comment]
Indeed, it is probably the most pragmatic short-term solution.

**Comment by akhmerov** [comment]
Fixed by [!7](https://gitlab.kwant-project.org/qt/topocm/merge_requests/7)

**Comment by akhmerov** [comment]
Closed too soon: Pelican skips the notebook:

```
ERROR: Could not process w2_majorana/Peierls.ipynb
  | Exception: Could not find metadata in `.ipynb-meta`, inside `.ipynb` or external `.md` file.
```

**Comment by basnijholt** [comment]
That means it's not in `with_output` https://github.com/topocm/topocm_content/blob/master/scripts/pelican_converter.py#L30

**Comment by akhmerov** [comment]
But [it is](https://gitlab.kwant-project.org/qt/topocm/builds/2179/artifacts/browse/generated/with_output/w2_majorana/).
