### ISSUE TITLE
Explore edx iframe components

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#181]
It should be possible to include our static materials on edx via iframes instead of course upload. This would greatly simplify updating the course.

**Comment by akhmerov** [comment]
Update: edx iframe components only work with https, which means we need to set up https (probably via letsencrypt) on topocondmat.org

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
