### ISSUE TITLE
Holoviews svg

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#182]
We should change the holoviews settings to produce svg, and not png figures.

**Comment by basnijholt** [comment]
Added in 5ac57bb4c5da91d3467fe0b3cc21e506532f4623.

Not sure if it works yet.

**Comment by basnijholt** [comment]
It works and it's beautiful! 🙏

**Comment by basnijholt** [comment]
Opening again because of this bug: https://github.com/ioam/holoviews/issues/947

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
