### ISSUE TITLE
Issues with the new website

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#188]
As [mentioned](https://gitlab.kwant-project.org/qt/topocm/merge_requests/4#note_1901) by Anton, there are problems with small screen (mobile) viewing:
- links escape to the page bottom
- widget controls are very narrow
- ~~video formatting is poor.~~

**Comment by akhmerov** [comment]
I've fixed the video formatting in 67985a2 and also the videos use 16x9 aspect ratio on any screen. For most course videos it was already the chosen resolution.
