### ISSUE TITLE
Remove arguments from init_mooc_nb

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#189]
Thanks to holoviews fixing https://github.com/ioam/holoviews/issues/599, we can remove the extra argument  `mpl=True` to `init_mooc_nb.init_notebook` once we can rely on holoviews >=1.6.2 (but right now we're blocked by https://github.com/ioam/holoviews/issues/805)

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
