### ISSUE TITLE
Small correction in section "The Kitaev chain model"

### ISSUE THREAD

**Issue by jdebruijckere** [topocm/topocm_content#192]
I think a -1 is missing on the right hand side of this expression:

$C^\dagger\,\tau_z\,\left|n\right\rangle\left\langle n\right|\,C = 2c_n^\dagger c_n$

should be

$C^\dagger\,\tau_z\,\left|n\right\rangle\left\langle n\right|\,C = 2c_n^\dagger c_n - 1$

if I am not mistaken..

**Comment by basnijholt** [comment]
@jdebruijckere thanks a lot for your keen eye!
