### ISSUE TITLE
Problem with adding matrices in notebooks hosted on Sage Cloud

### ISSUE THREAD

**Issue by acronheim** [topocm/topocm_content#193]
In the notebooks on http://tiny.cc/topocm_smc referred to from the assignment pages on https://topocondmat.org/, the following code does not run:

import sys
sys.path.append('../code')
from init_mooc_nb import *
init_notebook()

randn = np.random.randn

randn(2, 2) + 1j * randn(2, 2)

The problem does not occur in the current notebooks on github.

**Comment by akhmerov** [comment]
We no longer support SMC
