### ISSUE TITLE
Issue in week 5, Time-reversal symmetry and fermion parity pumps

### ISSUE THREAD

**Issue by davguy** [topocm/topocm_content#194]
Somewhere in the first lesson of the quantum spin hall effect lesson, the text reads:

"In the plot below, we show how this trajectory changes for our cylinder geometry as the BHZ model is driven through the topological phase transition. In the right panel, the green dots give you the phase of "
Then, there is a window where a plot should be. Instead, it's not shown and it displays the following error:

/opt/conda/lib/python3.5/site-packages/numpy/lib/twodim_base.py:233: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  m = zeros((N, M), dtype=dtype)
/opt/conda/lib/python3.5/site-packages/numpy/lib/twodim_base.py:240: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  m[:M-k].flat[i::M+1] = 1

**Comment by basnijholt** [comment]
Will be fixed once [this MR](https://gitlab.kwant-project.org/qt/topocm/merge_requests/24) is merged.
