### ISSUE TITLE
w1_topointro/0d.ipynb

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#209]
> We see that one level does cross zero (even twice)

Something has changed such that the bands do not cross `E=0`:

<img width="944" alt="screen shot 2018-02-02 at 12 48 43" src="https://user-images.githubusercontent.com/6897215/35731831-7c4a2bbe-0817-11e8-9274-d715e45eb0f0.png">

**Comment by akhmerov** [comment]
Maybe the details of the random number generator. Varying the seed should provide an easy fix.
