### ISSUE TITLE
Equation rendering issue on w8_general/invariants.md

### ISSUE THREAD

**Issue by andrenmelo** [topocm/topocm_content#227]
On `src/w8_general/invariants.md` the equation after

> This is a polynomial eigenvalue problem, and it is trivially mapped onto a standard eigenvalue problem.

is not being rendered correctly on [the topocm website](https://topocondmat.org/w8_general/invariants.html). I was not able to reproduce the bug locally, but I suspect fixing it is just a matter of removing the space in `- t_r` which is causing it to be rendered as a markdown list item.

**Comment by akhmerov** [comment]
Yeah, it's pretty much that, thanks for reporting. I'll double-check that it renders correctly with the fix and close this.
