### ISSUE TITLE
Typo in "Tight-binding models in a magnetic field: Peierls substitution"

### ISSUE THREAD

**Issue by elchatz** [topocm/topocm_content#228]
It seems to me there is a typo in 

https://topocondmat.org/w2_majorana/Peierls.html#Tight-binding-models-in-a-magnetic-field:-Peierls-substitution

A(r)→A(r)+∇A(r)  should probably read A(r)→A(r)+∇Λ(r)

and a parenthesis missing in the second RHS exponent of the Ht equation (2).

**Comment by akhmerov** [comment]
Thanks for reporting :)
