### ISSUE TITLE
Typo in 0D

### ISSUE THREAD

**Issue by longyangking** [topocm/topocm_content#236]
In the section “Hamiltonians, topology, and symmetry”, it has mentioned the topological invariant Q_{BdG} of BdG Hamiltonian under particle-hole symmetry, which is defined as Q_{BdG} = sign[Pf(i H_{BdG})]. However, the given H_{BdG} is not skew-symmetric so that the Pfaffian of H_{BdG} can not be calculated. According to the topological analysis demonstrated in this section, I think it should be \tilde{H}_{BdG}, namely, Q_{BdG} = sign[Pf(i \tilde{H}_{BdG})]. Is that right?

**Comment by akhmerov** [comment]
Thanks, fixed.
