### ISSUE TITLE
How to print the lattice figures in section "w12_manybody" such as toric_exchanges.svg?

### ISSUE THREAD

**Issue by zhg6290** [topocm/topocm_content#240]
Recently I want to draw some relevant figures about Toric code model for my thesis, but I have no idea how to draw a pretty figure like them in this online material.

**Comment by akhmerov** [comment]
I think these were originally drawn in intaglio, but any other vector graphics editing program (illustrator, inkscape) would work.

Also since our contents are licensed as creative commons, you may reuse figures as long as you credit the source.

**Comment by zhg6290** [comment]
Thanks for the reply!!!!
Yeah, I was wondering whether these figures were printed by python code. Actually, I have already used these figures in my thesis and I want to insert more to complete my details. For the uniformity and appearance, it would be much better to print the needed figures with the same way which produced the figures in topocond.org.

**Comment by akhmerov** [comment]
I think you can in principle make such figures automatically, but we didn't. If you manage—I'd be curious to see the code.

**Comment by zhg6290** [comment]
Got it, thanks a lot!
