### ISSUE TITLE
5.1 complex conjugation sign

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#35]
The $S^\dagger$ should be $S^T$ in:

![screen shot 2015-03-20 at 12 12 44](https://cloud.githubusercontent.com/assets/6897215/6750451/a7f0b48a-cefa-11e4-8f2e-955e2277543f.png)

**Comment by bernardvanheck** [comment]
Hi Bas - I think the equation is correct as it is. One should first apply S^+ to cancel S on the left side. Complex conjugation of the resulting equation then gives you $(S^+)* = S^T$ on the right side. Thanks for checking!
