### ISSUE TITLE
Typos in 1.2

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#4]
Reported by SamMugel

* in the first paragraph of Fermion operators and Majorana operators, the last c operator should be a c^\dagger
* in the section The Kitaev chain model, I think that when you give the formula you use to transform to the BdG Hamiltonian there is an extra factor of 2 in front of the (c^\dagger c) term

**Comment by SamMugel** [comment]
An additional issue: in Topological phases from the bulk spectrum, subsection Particle-hole symmetry in momentum space: conjugate( H(k) ) should not be H(-k). instead: conjugate( H(k) ) = transpose( H(-k) )

**Comment by akhmerov** [comment]
Second part isn't true because the onsite Majorana coupling was defined with a factor 1/2.
