### ISSUE TITLE
7.2  master/w7_defects/figures/vacancy.png doesn't exist on the server.

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#50]
404:

http://nbviewer.ipython.org/github/topocm/topocm_content/blob/master/w7_defects/figures/vacancy.png

**Comment by torosdahl** [comment]
Bump, this figure is still missing.

**Comment by irfanphy** [comment]
This figure (https://github.com/topocm/topocm_content/blob/master/w7_defects/figures/dislocation_chiral.svg) is not used in the notebook. I was wondering, if it can serve the purpose?

**Comment by akhmerov** [comment]
Can either draw a vacancy or borrow one from here: https://commons.wikimedia.org/wiki/Category:Defects_in_crystals

Before most wiki images weren't available to us because of the license, but we've joined the forces of good now.

**Comment by akhmerov** [comment]
BTW make use of the occasion and check if there are better images of other types of defects.

**Comment by akhmerov** [comment]
Closed via #143
