### ISSUE TITLE
Mistake in argument principle in w8_general/invariants.ipynb

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#53]
We can now use a nice result from complex analysis, the argument principle. it tells us that each zero of f(z) inside the unit circle contributes +1 to the value of Q(H), and each **zero** contributes −1.

Should be:

We can now use a nice result from complex analysis, the argument principle. it tells us that each zero of f(z) inside the unit circle contributes +1 to the value of Q(H), and each **pole** contributes −1.

**Comment by bernardvanheck** [comment]
fixed in 534216b07e5ac6ed9b6353b1ce030c3b93a0d3b6
