### ISSUE TITLE
Text markup mistake in w9_disorder/scaling.ipynb

### ISSUE THREAD

**Issue by basnijholt** [topocm/topocm_content#73]
Somewhere in the text:

 For $VV_c,conductancedecreaseswithsystemsize:thesystemisinsulating.HencebycomparingdifferentcurvesatfixedVwecaneasily′see′thesignofthe\beta$ function

**Comment by akhmerov** [comment]
What is the problem? To me it looks OK everywhere, and all the `$` are matched.

**Comment by basnijholt** [comment]
![screen shot 2015-04-23 at 08 49 23](https://cloud.githubusercontent.com/assets/6897215/7291830/b3f1f2b6-e995-11e4-8776-bd7dad028f0b.png)
