### ISSUE TITLE
1.1: explain the magic behind 4x4 Hamiltonian having 10 eigenvalues

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#75]

**Comment by irfanphy** [comment]
I have clarified only before first plot by mentioning a 10 x 10 Hamiltonian. 
I hope reader(s) will follow this for the rest of plots.

**Comment by akhmerov** [comment]
I'd add a clarification like "(we consider more levels here so that the spectrum looks more interesting)".

I notice now that the language version is stored in the notebook kernel metadata, which is OK for now, but will lead to merge conflicts eventually. We'll need to clean that out.
