### ISSUE TITLE
need schematic figure for Weyl in 10.1

### ISSUE THREAD

**Issue by jaysau** [topocm/topocm_content#78]
Concepts like Fermi Arcs at the surface of Weyl between Weyl points not quite obvious for students - probably need to illustrate by schematic.

**Comment by akhmerov** [comment]
@bernardvanheck as the course artist, can you give this a shot?

**Comment by bernardvanheck** [comment]
@akhmerov Sure, will do!

**Comment by akhmerov** [comment]
Looks quite good. Perhaps add a direction of propagation to the Fermi arcs? Together with labels and a clarification should be useful. Also perhaps rotate by pi/2 for the image to have a more common aspect ratio?

**Comment by bernardvanheck** [comment]
Added svg file. I am keeping the issue open just in case we need to make some more amends.

**Comment by akhmerov** [comment]
CLosed via #158
