### ISSUE TITLE
Implement calculating plots on checkout from the repository

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#87]
@minrk implemented a [prototype](https://github.com/minrk/delft-visit) for caching cell evaluation results and plugging them in on subsequent re-evaluations.

Right now it doesn't treat unicode well. We should implement it as a git filter, and stop storing the output inside the notebooks.

**Comment by torosdahl** [comment]
See a2f76e4

**Comment by akhmerov** [comment]
Sorry, ambiguous description, this issue is about using cache really. You have closed #80 instead.
