### ISSUE TITLE
Convert code to python 3.4

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#90]
It is a technical change and should be done as soon as Kwant 1.2.0 is out. It will also automatically close #74 since we'll stop importing from `__future__`.

**Comment by torosdahl** [comment]
The filters in #95 work with python 3 if the original cachedoutput.py script from Min is used. When we convert the code, we should thus switch to the original.

**Comment by akhmerov** [comment]
This is probably finished. Some issues may still linger, but we'll revisit them when working on the course.
